apiVersion: skaffold/v2alpha3
kind: Config
# all the config file [./infra/k8s] that we want to load into cluster
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # whenever we build an image do not try to push to dockerhub
  local:
    push: false
  artifacts:
    - image: jahidhiron/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      # how to handle skaffold if any file changes
      sync:
        manual:
          # watch skaffold any ts file under src folder and affect to pod directly
          - src: "src/**/*.ts"
            # where to sync inside of our running container > . means, where the file found and through
            # to corrosponding path inside the container
            dest: .
    - image: jahidhiron/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
