apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  # how to create individual pod during Deployment is going to create
  template:
    metadata:
      labels:
        app: tickets
    # how pod is going to behave
    spec:
      containers:
        - name: tickets # name of container
          image: jahidhiron/tickets
          env:
            - name: NATS_CLUSTER_ID
              value: ticketing
            # we are using pod name as nats client id
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  # select pod to access
  selector:
    app: tickets
  # all the ports that we are going to expose for that pod
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
